### ISSUE TITLE
SFML 2.3?

### ISSUE THREAD

**Issue by Nycto** [BlaXpirit/nim-csfml#7]
Any plans to regenerate the interface now SFML 2.3 is out? I'm really interested in seeing touch events included.

I gave the generate script a whirl, but encountered the following error:

```
Traceback (most recent call last):
  File "generate.py", line 417, in <module>
    Visitor().visit(ast)
  File "/usr/local/lib/python3.4/dist-packages/pycparser/c_ast.py", line 120, in visit
    return visitor(node)
  File "/usr/local/lib/python3.4/dist-packages/pycparser/c_ast.py", line 127, in generic_visit
    self.visit(c)
  File "/usr/local/lib/python3.4/dist-packages/pycparser/c_ast.py", line 120, in visit
    return visitor(node)
  File "generate.py", line 340, in visit_Typedef
    node.type.type.my_name = node.type.declname
AttributeError: 'Struct' object has no attribute 'my_name'
```

**Comment by Nycto** [comment]
Well, nevermind. I just answered my own question. I should have checked all your branches before filing a ticket; looks like this work is happening on master, and I was looking at the 2.2 branch.

Apologies for the noise!
